"""Initial tables

Revision ID: da4744d4d0e9
Revises: 
Create Date: 2024-11-13 16:41:31.177950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da4744d4d0e9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistants',
    sa.Column('assistant_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('system_prompt', sa.String(), nullable=False),
    sa.Column('user_prompt', sa.String(), nullable=False),
    sa.Column('first_message_prompt', sa.String(), nullable=True),
    sa.Column('middle_part_prompt', sa.String(), nullable=True),
    sa.Column('last_message_prompt', sa.String(), nullable=True),
    sa.Column('for_conversation', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('assistant_id')
    )
    op.create_table('ping_prompt',
    sa.Column('prompt_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ping_order_number', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('prompt_id')
    )
    op.create_table('services',
    sa.Column('service_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.create_table('telegram_clients',
    sa.Column('client_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_client_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('api_id', sa.String(), nullable=False),
    sa.Column('api_hash', sa.String(), nullable=False),
    sa.Column('app_version', sa.String(), nullable=False),
    sa.Column('device_model', sa.String(), nullable=False),
    sa.Column('system_version', sa.String(), nullable=False),
    sa.Column('lang_code', sa.String(length=2048), nullable=True),
    sa.Column('test_mode', sa.Boolean(), nullable=False),
    sa.Column('session_string', sa.String(length=2048), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('password', sa.String(length=2048), nullable=True),
    sa.Column('parse_mode', sa.String(), nullable=True),
    sa.Column('workdir', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('second_name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('tg_link', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_scam', sa.Boolean(), nullable=True),
    sa.Column('is_fake', sa.Boolean(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('last_online_date', sa.DateTime(), nullable=True),
    sa.Column('language_code', sa.String(), nullable=True),
    sa.Column('is_info', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('tg_user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('assistant_messages',
    sa.Column('assistant_message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('to_user_id', sa.BigInteger(), nullable=False),
    sa.Column('assistant_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_client_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistants.assistant_id'], ),
    sa.ForeignKeyConstraint(['telegram_client_id'], ['telegram_clients.client_id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.tg_user_id'], ),
    sa.PrimaryKeyConstraint('assistant_message_id')
    )
    op.create_table('research_owners',
    sa.Column('owner_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('second_name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('service_owner_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_link', sa.String(), nullable=True),
    sa.Column('last_online_date', sa.DateTime(), nullable=True),
    sa.Column('language_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.service_id'], ),
    sa.PrimaryKeyConstraint('owner_id')
    )
    op.create_table('user_messages',
    sa.Column('user_message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_user', sa.BigInteger(), nullable=False),
    sa.Column('chat', sa.BigInteger(), nullable=False),
    sa.Column('forwarded_from', sa.String(), nullable=True),
    sa.Column('reply_to_message_id', sa.Integer(), nullable=True),
    sa.Column('media', sa.Boolean(), nullable=False),
    sa.Column('edit_date', sa.DateTime(), nullable=True),
    sa.Column('voice', sa.Boolean(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['from_user'], ['users.tg_user_id'], ),
    sa.PrimaryKeyConstraint('user_message_id')
    )
    op.create_table('user_status',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('status_name', sa.Enum('FREE', 'WAIT', 'IN_PROGRESS', 'DONE', name='userstatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('researches',
    sa.Column('research_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('research_uuid', sa.String(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('descriptions', sa.String(), nullable=True),
    sa.Column('additional_information', sa.String(), nullable=True),
    sa.Column('assistant_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_client_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistants.assistant_id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['research_owners.owner_id'], ),
    sa.ForeignKeyConstraint(['telegram_client_id'], ['telegram_clients.client_id'], ),
    sa.PrimaryKeyConstraint('research_id')
    )
    op.create_table('voice_messages',
    sa.Column('voice_message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('file_unique_id', sa.String(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('file_size', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('user_message_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_message_id'], ['user_messages.user_message_id'], ),
    sa.PrimaryKeyConstraint('voice_message_id')
    )
    op.create_table('research_status',
    sa.Column('research_id', sa.BigInteger(), nullable=False),
    sa.Column('status_name', sa.Enum('WAIT', 'IN_PROGRESS', 'DONE', 'PAUSE', 'ABORTED', name='researchstatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['research_id'], ['researches.research_id'], ),
    sa.PrimaryKeyConstraint('research_id')
    )
    op.create_table('s3_voice_storage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('path', sa.String(length=2048), nullable=False),
    sa.Column('file_name', sa.String(length=2048), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('voice_messages_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['voice_messages_id'], ['voice_messages.voice_message_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_research',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('research_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['research_id'], ['researches.research_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'research_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_research')
    op.drop_table('s3_voice_storage')
    op.drop_table('research_status')
    op.drop_table('voice_messages')
    op.drop_table('researches')
    op.drop_table('user_status')
    op.drop_table('user_messages')
    op.drop_table('research_owners')
    op.drop_table('assistant_messages')
    op.drop_table('users')
    op.drop_table('telegram_clients')
    op.drop_table('services')
    op.drop_table('ping_prompt')
    op.drop_table('assistants')
    # ### end Alembic commands ###
