from pyrogram.types import Message


def message_to_dict(message: Message) -> dict:
    return {
        "id": message.id,
        "from_user": {
            "id": message.from_user.id,
            "is_bot": message.from_user.is_bot,
            "first_name": message.from_user.first_name,
            "last_name": message.from_user.last_name,
            "username": message.from_user.username,
            "language_code": message.from_user.language_code,
        } if message.from_user else None,
        "sender_chat": {
            "id": message.sender_chat.id,
            "type": message.sender_chat.type,
            "title": message.sender_chat.title,
            "username": message.sender_chat.username,
            "first_name": message.sender_chat.first_name,
            "last_name": message.sender_chat.last_name,
        } if message.sender_chat else None,
        "date": message.date,
        "chat": {
            "id": message.chat.id,
            "type": message.chat.type,
            "title": message.chat.title,
            "username": message.chat.username,
            "first_name": message.chat.first_name,
            "last_name": message.chat.last_name,
        },
        "forward_from": {
            "id": message.forward_from.id,
            "is_bot": message.forward_from.is_bot,
            "first_name": message.forward_from.first_name,
            "last_name": message.forward_from.last_name,
            "username": message.forward_from.username,
            "language_code": message.forward_from.language_code,
        } if message.forward_from else None,
        "forward_sender_name": message.forward_sender_name,
        "forward_from_chat": {
            "id": message.forward_from_chat.id,
            "type": message.forward_from_chat.type,
            "title": message.forward_from_chat.title,
            "username": message.forward_from_chat.username,
            "first_name": message.forward_from_chat.first_name,
            "last_name": message.forward_from_chat.last_name,
        } if message.forward_from_chat else None,
        "forward_from_message_id": message.forward_from_message_id,
        "forward_signature": message.forward_signature,
        "forward_date": message.forward_date,
        "reply_to_message": message_to_dict(message.reply_to_message) if message.reply_to_message else None,
        "via_bot": {
            "id": message.via_bot.id,
            "is_bot": message.via_bot.is_bot,
            "first_name": message.via_bot.first_name,
            "last_name": message.via_bot.last_name,
            "username": message.via_bot.username,
            "language_code": message.via_bot.language_code,
        } if message.via_bot else None,
        "text": message.text,
        "entities": [entity.to_dict() for entity in message.entities] if message.entities else None,
        "caption": message.caption,
        "caption_entities": [entity.to_dict() for entity in message.caption_entities] if message.caption_entities else None,
        "audio": message.audio.to_dict() if message.audio else None,
        "document": message.document.to_dict() if message.document else None,
        "photo": [photo.to_dict() for photo in message.photo] if message.photo else None,
        "sticker": message.sticker.to_dict() if message.sticker else None,
        "video": message.video.to_dict() if message.video else None,
        "voice": message.voice.to_dict() if message.voice else None,
        "video_note": message.video_note.to_dict() if message.video_note else None,
        "contact": message.contact.to_dict() if message.contact else None,
        "location": message.location.to_dict() if message.location else None,
        "venue": message.venue.to_dict() if message.venue else None,
        "poll": message.poll.to_dict() if message.poll else None,
        "dice": message.dice.to_dict() if message.dice else None,
        "new_chat_members": [user.to_dict() for user in message.new_chat_members] if message.new_chat_members else None,
        "left_chat_member": message.left_chat_member.to_dict() if message.left_chat_member else None,
        "new_chat_title": message.new_chat_title,
        "new_chat_photo": [photo.to_dict() for photo in message.new_chat_photo] if message.new_chat_photo else None,
        "delete_chat_photo": message.delete_chat_photo,
        "group_chat_created": message.group_chat_created,
        "supergroup_chat_created": message.supergroup_chat_created,
        "channel_chat_created": message.channel_chat_created,
        "migrate_to_chat_id": message.migrate_to_chat_id,
        "migrate_from_chat_id": message.migrate_from_chat_id,
        "pinned_message": message_to_dict(message.pinned_message) if message.pinned_message else None,
        "invoice": message.invoice.to_dict() if message.invoice else None,
        "successful_payment": message.successful_payment.to_dict() if message.successful_payment else None,
        "connected_website": message.connected_website,
        "reply_markup": message.reply_markup.to_dict() if message.reply_markup else None,
    }