
name: custdever stage workflow
on:
  workflow_dispatch:
  push:
    branches:
      - stage
jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
        - name: Get the code from repo
          uses: actions/checkout@v4
        - name: Install pipx
          run: pip install pipx
        - name: Install poetry
          run: pipx install poetry
        - name: Install dependencies
          run: poetry install --no-root
        - name: Run lint check
          run: poetry run ruff check --fix

    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_PASSWORD}}
        - name: Docker meta
          id: meta
          uses: docker/metadata-action@v5
          with:
            # list of Docker images to use as base name for tags
            images: |
              artemprod/sashka
            # generate Docker tags based on the following events/attributes
            tags: |
              type=ref,event=branch
              type=sha
        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            cache-from: type=gha
            cache-to: type=gha,mode=max
            context: .
            push: true
            tags: ${{steps.meta.outputs.tags}}


    cleanup:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set short sha
          id: set_sha
          run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

        - name: Load SSH aws key
          uses: webfactory/ssh-agent@v0.9.0
          with:
            ssh-private-key: ${{secrets.STAGE_PRIVATE_KEY}}

        - name: Add SSH key to known_hosts
          run: ssh-keyscan -H "${{vars.STAGE_HOST_ADDRESS}}" >> ~/.ssh/known_hosts

        - name: Create Docker Context
          run: docker context create custdever_stage_context --docker "host=ssh://${{ vars.STAGE_SSH_ADDRESS }}" || true

        - name: Check if services exist
          id: check_services
          run: |
            SERVICES_EXIST=$(docker --context custdever_stage_context ps -q --filter "name=custdever_api_getaway_main_worker" --filter "name=custdever_subscriber_researcher_worker" --filter "name=custdever_subscriber_communicator_worker" --filter "name=custdever_distributor")
            echo "Services Exist: $SERVICES_EXIST"
            if [ -n "$SERVICES_EXIST" ]; then
              echo "true"
            else
              echo "false"
            fi | tee /tmp/services_exist.txt
            echo "::set-output name=services_exist::$(cat /tmp/services_exist.txt)"

        - name: Cleanup services if they exist
          if: steps.check_services.outputs.services_exist == 'true'
          run: |
            echo "${{ vars.STAGE_ENV_FILE }}" >> ./deploy/stage/.env
            docker --context custdever_stage_context compose -f deploy/stage/docker-compose.yml down
            docker --context custdever_stage_context system prune -af
            if ! docker --context custdever_stage_context network ls --filter name=custdever_stage_network --format '{{.Name}}' | grep -w custdever_stage_network; then
            docker --context custdever_stage_context network create custdever_stage_network
            fi
#

    deploy:
      needs: cleanup
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
          with:
            sparse-checkout: |
              deploy
            sparse-checkout-cone-mode: false


        - name: Set short sha
          id: set_sha
          run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

        - name: Load SSH aws key
          uses: webfactory/ssh-agent@v0.9.0
          with:
            ssh-private-key: ${{secrets.STAGE_PRIVATE_KEY}}

        - name: Add SSH key to known_hosts
          run: ssh-keyscan -H "${{vars.STAGE_HOST_ADDRESS}}" >> ~/.ssh/known_hosts

        - name: Create Docker Context
          run: docker context create custdever_stage_context --docker "host=ssh://${{ vars.STAGE_SSH_ADDRESS }}" || true

        - name: Ensure remote directory exists
          run: |
            ssh -o StrictHostKeyChecking=no ${{ vars.STAGE_SSH_ADDRESS }} "mkdir -p /remote/nats/config/"

        - name: Copy nats config to remote server
          run: |
            scp -o StrictHostKeyChecking=no deploy/stage/nats/config/server.conf ${{ vars.STAGE_SSH_ADDRESS }}:/remote/nats/config/

        - name: Deploy
          run: |
            echo "${{ vars.STAGE_ENV_FILE }}" >> ./deploy/stage/.env
            export IMAGE_TAG=sha-${{ steps.set_sha.outputs.sha_short }}
            docker --context custdever_stage_context compose -f deploy/stage/docker-compose.yml up -d --wait --wait-timeout 60
          
          
          
